=== cietwwl/webgame/game_tools/config/msg/model/message.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://com.imop.tr.message"
	xmlns:tns="http://com.imop.tr.message" elementFormDefault="qualified">
	<element name="messages" type="tns:messages"></element>

	<complexType name="messages">
		<sequence>
			<element name="constants" type="tns:constants" maxOccurs="1"
				minOccurs="0"></element>
			<element name="message" type="tns:message" maxOccurs="unbounded"
				minOccurs="0"></element>
		</sequence>
		<attribute name="module" type="string"></attribute>
		<attribute name="server" type="string"></attribute>
	</complexType>

	<complexType name="message">
		<sequence>
			<element name="field" type="tns:field" maxOccurs="unbounded"
				minOccurs="0">
			</element>
		</sequence>
		<attribute name="type" type="string"></attribute>
		<attribute name="comment" type="string"></attribute>
		<attribute name="friendQueue" type="tns:onlytrue" fixed="true"></attribute>
		<attribute name="guildQueue" type="tns:onlytrue" fixed="true"></attribute>
		<attribute name="macro" type="string"></attribute> 
	</complexType>

	<complexType name="constants">
		<sequence>
			<element name="constant" type="tns:constant" maxOccurs="unbounded"
				minOccurs="0">
			</element>
		</sequence>
	</complexType>

	<complexType name="constant">
		<simpleContent>
			<extension base="string">
				<attribute name="name" type="string"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="field">
		<sequence>
			<element name="field" type="tns:field" maxOccurs="unbounded"
				minOccurs="0">
			</element>
		</sequence>
		<attribute name="type" type="string"></attribute>
		<attribute name="clientType" type="string"></attribute>
		<attribute name="name" type="string"></attribute>
		<attribute name="list" type="tns:onlytrue" fixed="true"></attribute>
		<attribute name="comment" type="string"></attribute>
		<attribute name="macro" type="string"></attribute>
		<attribute name="subMsg" type="tns:onlytrue"></attribute>
		<attribute name="defalutValue" type="string"></attribute>
	</complexType>

	<simpleType name="onlytrue">
		<restriction base="string">
			<enumeration value="true"></enumeration>
		</restriction>
	</simpleType>
</schema>

=== cietwwl/webgame/game_tools/config/msg/model/skill_message.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="skill">
	<message type="CG_Skill_Upgrade" comment="技能升级消息">
		<field type="String" name="skillSn" comment="技能sn"></field>
		<field type="Integer" name="rank" comment="等级"></field>
	</message>

	<message type="GC_Skill_Upgrade" comment="技能升级消息">
		<field type="String" name="skillSn" comment="技能sn"></field>
		<field type="Integer" name="rank" comment="等级"></field>
	</message>

	<message type="CG_Skill_Order" comment="修改技能组">
		<field type="Integer" name="vocationType" comment="职业类型"></field>
		<field type="Integer" name="skillGroupOrder" comment="技能组编号"></field>
		<field type="String" name="skillGroupName" comment="技能组名称"></field>
		<field type="String" name="skillSns" comment="技能sn序列" list="true"></field>
	</message>

	<message type="GC_Skill_Group_Name" comment="修改技能组名称">
		<field type="Integer" name="vocationType" comment="职业类型"></field>
		<field type="Integer" name="skillGroupOrder" comment="技能组编号"></field>
		<field type="String" name="skillGroupName" comment="技能组名称"></field>
	</message>

	<message type="GC_Skill_Order" comment="修改技能组顺序">
		<field type="Integer" name="vocationType" comment="职业类型"></field>
		<field type="Integer" name="skillGroupOrder" comment="技能组编号"></field>
		<field type="String" name="skillSns" comment="技能sn序列" list="true"></field>
	</message>

	<message type="CG_Skill_Cooldown" comment="技能冷却加速">
		<field type="String" name="cdSn" comment="cdSn"></field>
		<field type="String" name="accelerateTime" comment="加速的时间"></field>
		<field type="Integer" name="currencyType" comment="货币类型 0为元宝"></field>
		<field type="Integer" name="currencyNumber" comment="货币数量"></field>
	</message>

	<message type="GC_Skill_Cooldown" comment="技能冷却加速">
		<field type="String" name="cdSn" comment="cdSn"></field>
		<field type="Integer" name="cdType"
			comment="cd类型 0 表示增加冷却 1表示加速修改冷却 2表示冷却时间到了结束冷却"></field>
		<field type="Integer" name="targetType" comment="冷却对象类型，如：0表示技能冷却"></field>
		<field type="String" name="targetSn" comment="冷却对象sn"></field>
		<field type="String" name="cooldownTime" comment="剩余冷却时间"></field>
		<field type="Integer" name="currencyType" comment="货币类型 0为元宝"></field>
		<field type="Integer" name="currencyNumber" comment="货币数量"></field>
	</message>

</messages>

=== cietwwl/webgame/game_tools/config/msg/model/day_task_message.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="dayTask">

	<message type="CG_DAY_TASK_INFO" comment="查询任务列表">
	</message>
	
	<message type="GC_DAY_TASK_INFO" comment="返回任务列表">
		<field type="Integer" name="number" comment="剩余弹药数"></field>
		<field type="Boolean" name="isInTask" comment="是否在任务中"></field>
		<field type="String" name="taskId" comment="任务id"></field>
		<field type="Integer" name="curTimes" comment="当前次数"></field>
	</message>
	
	<message type="CG_GET_NEW_TASK" comment="领取新任务">
	</message>
	
	<message type="GC_GET_NEW_TASK" comment="返回任务信息">
		<field type="Boolean" name="success" comment="是否领取成功"></field>
		<field type="String" name="desc" comment="失败原因描述"></field>
		<field type="Integer" name="number" comment="剩余弹药数"></field>
		<field type="String" name="taskId" comment="任务id"></field>
		<field type="Integer" name="curTimes" comment="当前次数"></field>
	</message>
	
	<message type="CG_DAY_TASK_DROP" comment="放弃任务">
		<field type="String" name="taskId" comment="任务id"></field>
	</message>
	
	<message type="GC_DAY_TASK_DROP" comment="返回放弃任务信息">
		<field type="Boolean" name="result" comment="结果"></field>
		<field type="String" name="description" comment="描述"></field>
	</message>
	
	<message type="GC_DAY_TASK_COMPLETE" comment="返回任务完成信息">
		<field type="String" name="taskId" comment="任务id"></field>
	</message>
</messages>

=== cietwwl/webgame/game_tools/config/msg/model/arena_message.xml
<?xml version="1.0" encoding="utf-8" ?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="arena">
	
	<!-- 客户端请求获取竞技场信息  -->
	<message type="CG_ARENA_LIST" comment="获取竞技场信息">
	</message>
	
	<!-- 返回竞技场信息 -->
	<message type="GC_ARENA_LIST" comment="返回竞技场信息">
		<field type="String" name="title" comment="称号" />
		<field type="Integer" name="rank" comment="排名" />
		<field type="Integer" name="win" comment="连胜" />
		<field type="Integer" name="challenge" comment="剩余挑战次数" />
		<field type="com.pwrd.war.gameserver.arena.ArenaRoleInfo" clientType="ArenaRoleInfo"  name="targets" comment="目标信息" list="true" macro="arenaRoleInfo" />
		<field type="com.pwrd.war.gameserver.arena.ChallengeHistory" clientType="ChallengeHistory"  name="challenges" comment="挑战历史" list="true" macro="arenaChallengeHistory" />
		<field type="com.pwrd.war.gameserver.arena.TopHistory" clientType="TopHistory"  name="tops" comment="巅峰之战历史" list="true" macro="arenaTopHistory" />
		<field type="String" name="msg" comment="吐槽" />
	</message>
	
	<!-- 客户端请求挑战信息 -->
	<message type="CG_ARENA_FIGHT" comment="竞技场挑战">
		<field type="Integer" name="targetPos" comment="挑战目标位置" />
	</message>
	
	<!-- 客户端请求排行榜 -->
	<message type="CG_ARENA_RANKING_LIST" comment="获取竞技场排行榜信息">
	</message>
	
	<!-- 返回竞技场排行榜信息 -->
	<message type="GC_ARENA_RANKING_LIST" comment="返回竞技场排行榜信息">
		<field type="com.pwrd.war.gameserver.arena.RankingInfo" clientType="RankingInfo"  name="ranking" comment="排行信息" list="true" macro="arenaRanking" />
		<field type="com.pwrd.war.gameserver.arena.WinRankingInfo" clientType="WinRankingInfo"  name="win" comment="连胜排行信息" list="true" macro="arenaWinRanking" />
	</message>
	
	<!-- 客户端请求成就 -->
	<message type="CG_ARENA_ACHIEVEMENT_LIST" comment="获取竞技场成就信息">
	</message>
	
	<!-- 返回竞技场成就信息 -->
	<message type="GC_ARENA_ACHIEVEMENT_LIST" comment="返回竞技场成就信息">
		<field type="com.pwrd.war.gameserver.arena.ArenaAchievement" clientType="ArenaAchievement"  name="achievement" comment="成就" list="true" macro="arenaAchievement" />
	</message>
	
	<!-- 付费增加攻击次数上限信息 -->
	<message type="CG_ARENA_ADD_TIME" comment="增加竞技场挑战次数">
	</message>
	
	<!-- 修改吐槽信息 -->
	<message type="CG_ARENA_UPDATE_MSG" comment="修改吐槽信息">
		<field type="String" name="msg" comment="吐槽" />
	</message>
	
	<!-- 增加竞技场次数结果消息 -->
	<message type="GC_ARENA_ADD_TIME" comment="增加竞技场次数结果消息">
		<field type="Integer" name="curTime" comment="当前已经增加的次数" />
		<field type="Integer" name="nextCost" comment="下一次消耗的花费数" />
	</message>
	
	<!-- 竞技场公告 -->
	<message type="GC_ARENA_NOTICE" comment="竞技场公告">
		<field type="String" name="msg" comment="公告内容" />
	</message>
</messages>

=== cietwwl/webgame/game_tools/config/msg/model/friend_message.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="friend">

	<message type="CG_FRIEND_ADD" comment="添加好友"> 
		<field type="String" name="friendName" comment="名字"></field> 
	</message>
 	
 	<message type="CG_FRIEND_GET_LIST" comment="获取好友列表"> 
	</message>
	<message type="CG_FRIEND_DEL" comment="删除好友"> 
		<field type="String" name="friendUUID" comment="好友UUID"></field> 
	</message>
	<message type="CG_FRIEND_ADD_BLACK" comment="加入屏蔽"> 
		<field type="String" name="friendUUID" comment="好友UUID"></field> 
	</message>
	<message type="CG_FRIEND_DEL_BLACK" comment="取消屏蔽"> 
		<field type="String" name="friendUUID" comment="好友UUID"></field> 
	</message>
	
	<message type="GC_FRIEND_LIST" comment="获返回好友列表"> 
		<field type="com.pwrd.war.gameserver.friend.FriendInfo"  
		        clientType="FriendInfo" name="friends" list="true" comment="好友信息列表" macro="friendInfo">  
		</field>
 	</message>
 	
 	<message type="GC_FRIEND_NEW_MESSAGE" comment="有新的离线消息"> 
 		<field type="com.pwrd.war.gameserver.friend.FriendInfo"  
		        clientType="FriendInfo" name="messages" list="true" comment="好友信息列表" macro="friendInfo">    
		</field>
 	</message>
 	
 	<message type="GC_FRIEND_ADD_OR_UPDATE" comment="好友信息更新"> 
 		<field type="com.pwrd.war.gameserver.friend.FriendInfo"  
		        clientType="FriendInfo" name="info"  comment="好友信息" macro="friendInfo"/>   
 	</message> 	
 	<message type="GC_FRIEND_DEL" comment="好友信息删除">
 		<field type="String" name="friendUUID" comment="好友UUID"></field> 
 	</message>
 	
 	
 	<message type="GC_FRIEND_LATEST_LINK" comment="最近联系人列表"> 
		<field type="com.pwrd.war.gameserver.friend.FriendInfo"  
		        clientType="FriendInfo" name="players" list="true" comment="用户信息列表" macro="friendInfo">  
		</field>
 	</message>
 	<message type="GC_FRIEND_LATEST_ADD_OR_UPDATE" comment="最近联系人信息更新"> 
 		<field type="com.pwrd.war.gameserver.friend.FriendInfo"  
		        clientType="FriendInfo" name="info"  comment="玩家信息" macro="friendInfo"/>   
 	</message>
 	<message type="GC_FRIEND_LATEST_DEL" comment="最近联系玩家信息删除">
 		<field type="String" name="friendUUID" comment="好友UUID"></field> 
 	</message>
 	
 	
 	<message type="GC_FRIEND_BLACK_ADD" comment="黑名单增加"> 
 		<field type="String" name="friendUUID" comment="好友UUID"></field> 
		<field type="String" name="friendName" comment="好友名字"></field> 
 	</message> 	
 	<message type="GC_FRIEND_BLACK_DEL" comment="黑名单信息删除">
 		<field type="String" name="friendUUID" comment="好友UUID"></field> 
 	</message> 	
 	<message type="GC_FRIEND_BLACKS" comment="黑名单列表"> 
		<field type="com.pwrd.war.gameserver.friend.FriendInfo"  
		        clientType="FriendBlackInfo" name="players" list="true" comment="用户信息列表" >  
		        <field type="String" name="friendUUID" comment="好友UUID"></field> 
		        <field type="String" name="friendName" comment="好友名字"></field> 
		</field>
 	</message>
 	
 	<message type="CG_FRIEND_GET_INFO" comment="获取玩家信息">
 		<field type="String" name="friendUUID" comment="好友UUID"></field> 
 	</message> 	
 	<message type="GC_FRIEND_GET_INFO" comment="获取玩家信息">
 		<field type="com.pwrd.war.gameserver.friend.FriendInfo"  
		        clientType="FriendInfo" name="info"  comment="玩家信息" macro="friendInfo"/> 
 	</message> 	
 	<message type="GC_FRIEND_ADD_RES" comment="增加好友结果反馈">
 		<field type="Boolean" name="result" comment="结果"></field> 
 		<field type="String" name="friendUUID" comment="好友UUID"></field> 
 	</message>
 	
</messages>

=== cietwwl/webgame/game_tools/config/msg/model/interactive.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="interactive">
	<message type="CG_Look_Up_Message" comment="查看别人的信息消息">
		<field type="String" name="playUUID" comment="玩家的UUID"></field>
	</message>
	<message type="GC_Look_Up_Message" comment="查看别人的信息的返回消息">
		<field type="String" name="playUUID" comment="玩家的UUID"></field>
		<field type="String" name="name" comment="玩家名称"></field>
		<field type="Integer" name="sex" comment="性别"></field>
		<field type="Integer" name="vocation" comment="性别"></field>
		<field type="Integer" name="level" comment="性别"></field>
		<field type="Integer" name="openFunction"
			comment="开启功能（聊天功能: 0x0001,基本信息:0x0002,切磋功能:0x0004,加好友功能:0x0008）"></field>
	</message>

	<message type="CG_Role_List_Message" comment="查看装备基本信息">
		<field type="String" name="playUUID" comment="玩家的UUID"></field>
	</message>


	<message type="GC_Role_List_Message" comment="查看装备基本信息">
		<field type="String" name="playUUID" comment="玩家的UUID"></field>
		<field type="com.pwrd.war.gameserver.interactive.domain.PetInfomation"
			name="petInformation" clientType="PetInformation" list="true"
			macro="PetInformation"></field>
	</message>
	
	<message type="CG_Equipment_Infomation_Message" comment="查看装备基本信息">
		<field type="String" name="playUUID" comment="玩家的UUID"></field>
		<field type="String" name="roleSn" comment="角色UUID"></field>
	</message>

	<message type="CG_Infomation_Message" comment="查看信息">
		<field type="String" name="playUUID" comment="玩家的UUID"></field>
		<field type="String" name="roleSn" comment="角色UUID"></field>
	</message>

	<message type="GC_Infomation_Message" comment="查看信息">
		<field type="String" name="playUUID" comment="玩家的UUID"></field>
		<field type="String" name="roleSn" comment="角色UUID"></field>
	</message>

	<message type="CG_Transfer_Vocation_Information_Message" comment="查看转职信息">
		<field type="String" name="playUUID" comment="玩家的UUID"></field>
		<field type="String" name="roleSn" comment="角色UUID"></field>
	</message>
</messages>

=== cietwwl/webgame/game_tools/config/msg/model/common_message.xml
<?xml version="1.0" encoding="utf-8" ?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="common">
	<constants>
		<constant name="消息显示类型">
			1- 普通消息类
			2-	重要消息类
			3-在当前对话窗口直接显示此信息 
			4-在好友闪动处显示 
		</constant>
	</constants>
	<message type="GC_SYSTEM_MESSAGE" comment="系统提示消息">
		<field type="String" name="content" comment="消息内容"></field>
		<field type="Integer" name="color" comment="消息字体颜色"></field>
		<field type="Short" name="showType" comment="消息显示类型"></field>
	</message>

	<message type="GC_SYSTEM_NOTICE" comment="系统公告">
		<field type="String" name="content" comment="消息内容"></field>
		<field type="Integer" name="color" comment="消息字体颜色"></field>
		<field type="Short" name="speed" comment="速度"></field>
		<field type="Short" name="time" comment="显示时长"></field>
	</message>

	<message type="GC_WAITING_START" comment="等待开始">
		<field type="Integer" name="waitingType" comment="等待类型,如创建副本等待"></field>
		<field type="Integer" name="overTime" comment="超时时间（秒）"></field>
		<field type="String" name="title" comment="等待标题"></field>
		<field type="String" name="tip" comment="等待提示语"></field>
	</message>
	
	<message type="GC_WAITING_OVER" comment="等待结束">
		<field type="Integer" name="waitingType" comment="等待类型"></field>
		<field type="Integer" name="tag" comment="标签,该等待的一个标识"></field>
	</message>
	
	<message type="CG_PING" comment="客户端用于时间同步的消息">
	</message>
	
	<message type="GC_PING" comment="服务器端响应的时间同步的消息">
		<field type="Long" name="timestamp" comment="服务器当前时间戳"></field>
	</message>
	
	<message type="GC_HANDSHAKE" comment="服务器准备好之后,告知客户端可以进行登录操作">		
	</message>

	<message type="GC_SHOW_OPTION_DLG" comment="显示确认对话框">
		<field type="String" name="title" comment="窗口标题" />
		<field type="String" name="content" comment="窗口内容" />
		<field type="String" name="tag" comment="操作标识" />
		<field type="String" name="okText" />
		<field type="String" name="cancelText" />
	</message>

	<message type="CG_SELECT_OPTION" comment="选择确认对话框 ok 或 cancel 选项">
		<field type="String" name="tag" comment="操作标识" />
		<field type="String" name="value" comment="选项值" />
	</message>
	
	<message type="GC_COMMON_ASK_AND_ANSWER_URL" comment="在线答疑URL">
		<field type="String" name="url" comment="URL值"></field>
	</message>
	
	<message type="GC_SYSTEM_PROMPT" comment="提示消息:1:重要提示(个人提示)2:错误提示3:按钮提示4:头顶提示5:特殊提示">
		<field type="Short" name="showType" comment="消息类型"></field>
		<field type="String" name="content" comment="消息内容"></field>
		<field type="Integer" name="color" comment="消息字体颜色"></field>
	</message>

</messages>

=== cietwwl/webgame/game_tools/config/msg/model/vocation_message.xml
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="vocation">
	<message type="GC_Vocation" comment="职业">
		<field type="com.pwrd.war.gameserver.vocation.VocationSkill"
			name="vocationSkills" clientType="VocationSkill" list="true" macro="VocationSkill"></field>
	</message>
	<message  type="CG_Default_Skill_Group" comment="设置默认技能组">
	   <field type="Integer" name="vocationType" comment="职业类型"></field>
	   <field type="Integer" name="defaultSkillGroupOrder" comment="默认技能组编号"></field>
	</message>
	<message  type="GC_Default_Skill_Group" comment="设置默认技能组返回">
	   <field type="Integer" name="vocationType" comment="职业类型"></field>
	   <field type="Integer" name="defaultSkillGroupOrder" comment="默认技能组编号"></field>
	</message>
</messages>

=== cietwwl/webgame/game_tools/config/msg/model/prize_message.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="prize">
	
	<message type="CG_PRIZE_PLATFORM_LIST" comment="查询平台玩家奖励列表">	
	</message>
	
	<message type="GC_PRIZE_PLATFORM_LIST" comment="返回平台玩家奖励列表">
		<field type="com.pwrd.war.gameserver.prize.PlatformPrizeHolder"
			name="prizes" list="true" comment="奖励列表">
			<field type="Integer" name="uniqueId" comment="平台奖励唯一编号"></field>
			<field type="Integer" name="prizeId" comment="奖励编号"></field>
			<field type="String" name="prizeName" comment="奖励名称"></field>
		</field>
	</message>

	<message type="CG_PRIZE_PLATFORM_GET" comment="领取奖励">
		<field type="Integer" name="uniqueId" comment="平台奖励唯一编号"></field>
		<field type="Integer" name="prizeId" comment="奖励编号"></field>
	</message>

	<message type="GC_PRIZE_PLATFORM_GET_SUCCESS" comment="领取平台奖励成功">
		<field type="Integer" name="uniqueId" comment="平台奖励唯一编号"></field>
	</message>
	
	<message type="CG_PRIZE_USER_LIST" comment="查询GM补偿的奖励列表">	
	</message>
	
	<message type="GC_PRIZE_USER_LIST" comment="玩家奖励列表">
		<field type="com.pwrd.war.gameserver.prize.UserPrizeInfo"
			name="prizes" list="true" comment="奖励列表">
			<field type="Integer" name="prizeId" comment="奖励ID"></field>
			<field type="String" name="prizeName" comment="奖励名称"></field>
		</field>
	</message>
	
	<message type="CG_PRIZE_USER_GET" comment="领取玩家奖励">
		<field type="Integer" name="prizeId" comment="奖励编号"></field>
	</message>
	
	<message type="GC_PRIZE_USER_GET_SUCCESS" comment="领取奖励成功">
		<field type="Short" name="prizeType" comment="奖励类型，1-系统补偿"></field>
		<field type="Integer" name="prizeId" comment="奖励ID"></field>
	</message>
	
	

</messages>
