=== cietwwl/webgame/game_tools/config/msg/model/message.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://com.imop.tr.message"
	xmlns:tns="http://com.imop.tr.message" elementFormDefault="qualified">
	<element name="messages" type="tns:messages"></element>

	<complexType name="messages">
		<sequence>
			<element name="constants" type="tns:constants" maxOccurs="1"
				minOccurs="0"></element>
			<element name="message" type="tns:message" maxOccurs="unbounded"
				minOccurs="0"></element>
		</sequence>
		<attribute name="module" type="string"></attribute>
		<attribute name="server" type="string"></attribute>
	</complexType>

	<complexType name="message">
		<sequence>
			<element name="field" type="tns:field" maxOccurs="unbounded"
				minOccurs="0">
			</element>
		</sequence>
		<attribute name="type" type="string"></attribute>
		<attribute name="comment" type="string"></attribute>
		<attribute name="friendQueue" type="tns:onlytrue" fixed="true"></attribute>
		<attribute name="guildQueue" type="tns:onlytrue" fixed="true"></attribute>
		<attribute name="macro" type="string"></attribute> 
	</complexType>

	<complexType name="constants">
		<sequence>
			<element name="constant" type="tns:constant" maxOccurs="unbounded"
				minOccurs="0">
			</element>
		</sequence>
	</complexType>

	<complexType name="constant">
		<simpleContent>
			<extension base="string">
				<attribute name="name" type="string"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="field">
		<sequence>
			<element name="field" type="tns:field" maxOccurs="unbounded"
				minOccurs="0">
			</element>
		</sequence>
		<attribute name="type" type="string"></attribute>
		<attribute name="clientType" type="string"></attribute>
		<attribute name="name" type="string"></attribute>
		<attribute name="list" type="tns:onlytrue" fixed="true"></attribute>
		<attribute name="comment" type="string"></attribute>
		<attribute name="macro" type="string"></attribute>
		<attribute name="subMsg" type="tns:onlytrue"></attribute>
		<attribute name="defalutValue" type="string"></attribute>
	</complexType>

	<simpleType name="onlytrue">
		<restriction base="string">
			<enumeration value="true"></enumeration>
		</restriction>
	</simpleType>
</schema>

=== cietwwl/webgame/game_tools/config/msg/model/rep_message.xml
<?xml version="1.0" encoding="utf-8" ?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="rep">
	<!-- 返回用户副本信息列表 -->
	<message type="CG_REP_INFO_LIST" comment="玩家副本列表">
		<field type="String" name="sceneId" comment="场景Id" />
	</message> 
	<!-- 返回用户副本信息列表结果 -->
	<message type="GC_REP_INFO_LIST" comment="玩家副本列表">
		<field type="com.pwrd.war.common.model.rep.RepInfoList" 
			clientType="RepInfoListData" name="repInfoList" list="true" comment="用户副本信息列表" macro="RepInfoList" ></field>
	</message> 
	<!-- 创建副本 -->
	<message type="CG_CREATE_REP" comment="玩家创建副本">
		<field type="String" name="repId" comment="副本 Id" />
		<field type="String" name="switchSenceId" comment="切换点id"></field>
	</message> 
 	<!-- 创建副本结果 -->
 	<message type="GC_CREATE_REP" comment="发给玩家创建副本结果">
 		<field type="String" name="repUuid" comment="UUID"></field>
 	    <field type="String" name="repId" comment="副本 Id" />
 	    <field type="String" name="senceId" comment="目标场景id"></field>
 	    <field type="String" name="swtichId" comment="目标场景切换点id"></field>
		<field type="Boolean" name="result" comment="进入结果"></field>
		<field type="String" name="reason" comment="原因"></field>
	</message> 
	<!-- 进入副本-->
	<message type="CG_ENTRY_REP" comment="进入副本">
		<field type="String" name="repUuid" comment="副本id"></field>
	</message> 
	<!-- 进入副本结果 -->
	<message type="GC_ENTRY_REP" comment="进入副本结果">
		<field type="String" name="repId" comment="副本id"></field>
		<field type="Boolean" name="result" comment="进入结果"></field>
		<field type="String" name="reason" comment="原因"></field>
	</message> 
	<!-- 完成副本 -->
	<message type="GC_COMPLETE_REP" comment="离开副本">
		<field type="Boolean" name="result" comment="完成结果"></field>
	</message>
	<!-- 副本奖励信息 -->
	<message type="GC_PRIZE_INFO" comment="副本奖励信息">
		<field type="Integer" name="atkScore" comment="攻击分"></field>
		<field type="Integer" name="defScore" comment="防御分"></field>
		<field type="Integer" name="money" comment="奖励铜钱"></field>
		<field type="Integer" name="exp" comment="奖励经验"></field>
		<field type="Integer" name="see" comment="奖励阅历"></field>
		<field  type="String" name="itemSn" list="true" comment="掉落的物品sn，数量都为1"></field>
		<field type="Integer" name="gold" comment="奖励元宝"></field>
	</message>
	<!-- 获得奖励 -->
	<message type="CG_GET_PRIZE" comment="离开副本">
	</message>
	<!-- 获得奖励 -->
	<message type="GC_GET_PRIZE" comment="离开副本">
	</message>
	<!-- 拾取物品 -->
	<message type="CG_SHIQU_ITEM" comment="离开副本">
		<field type="Boolean" name="getPrize" comment="是否领取了奖励"></field>
	</message>
	<!-- 拾取物品结果 -->
	<message type="GC_SHIQU_ITEM" comment="离开副本">
		<field type="Boolean" name="result" comment="拾取结果"></field>
		<field type="String" name="desc" comment="结果描述"></field>
	</message>
	<!-- 离开副本 -->
	<message type="CG_LEAVE_REP" comment="离开副本">
		<field type="Boolean" name="getPrize" comment="是否领取了奖励"></field>
	</message>
	<!-- 离开副本结果 -->
	<message type="GC_LEAVE_REP" comment="离开副本">
		<field type="String" name="sceneId" comment="原来场景id"></field>
		<field type="Integer" name="X" comment="X坐标"></field>
		<field type="Integer" name="Y" comment="Y坐标"></field>
	</message>
	<!-- 离开副本结果 -->
	<message type="GC_ALIVE_MONSTER" comment="剩余怪物数量">
		<field type="Integer" name="num" comment="剩余怪物数量"></field>
	</message>
	
	<!-- 请求副本扫荡信息 -->
	<message type="CG_AGAINST_REP_INFO" comment="获取请求扫荡副本信息">
		<field type="String" name="repId" comment="副本id"></field>
	</message> 
	<message type="GC_AGAINST_REP_INFO" comment="返回请求扫荡副本信息">
		<field type="String" name="repId" comment="副本id"></field>
		<field type="Integer" name="battleTimes" comment="战斗次数"></field>
		<field type="Integer" name="zhandouli" comment="战斗力"></field>
		<field type="Integer" name="bagIdleNum" comment="背包空闲数"></field>
		<field type="String" name="againstInfo" comment="扫描对象"></field>
	</message> 
	<!-- 请求副本挂机 -->
	<message type="CG_AGAINST_REP_START" comment="开始扫荡副本">
		<field type="String" name="repId" comment="副本id"></field>
		<field type="Integer" name="times" comment="轮数，0(消耗全部体力),4(30分钟4轮),8(1小时8轮)"></field>
	</message>
	<!-- 开始扫荡挂机 -->
	<message type="GC_AGAINST_REP_START" comment="开始扫荡副本">
		<field type="String" name="repId" comment="副本id"></field>
		<field type="String" name="repName" comment="副本名称"></field>
		<field type="Integer" name="cycle" comment="轮数"></field>
		<field type="Integer" name="cycleTime" comment="次数"></field>
		<field type="Integer" name="leftTimes" comment="剩余战斗次数"></field>
		<field type="Integer" name="leftTime" comment="剩余时间"></field>
		<field type="Integer" name="zhandouli" comment="战斗力"></field>
		<field type="Integer" name="bagIdleNum" comment="背包空闲数"></field>
		<field type="String" name="againstInfo" comment="扫描对象"></field>
	</message>
	<!-- 每次扫荡结果消息 -->
	<message type="GC_AGAINST_REP_RESULT" comment="扫荡副本结果信息">
		<field type="String" name="repId" comment="副本id"></field>
		<field type="Integer" name="leftTime" comment="剩余时间，单位为秒,为0表示结束"></field>
		<field type="Integer" name="leftTimes" comment="剩余战斗次数"></field>
		<field type="Integer" name="zhandouli" comment="战斗力"></field>
		<field type="Integer" name="bagIdleNum" comment="背包空闲数"></field>
		<field type="Integer" name="cycle" comment="轮"></field>
		<field type="Integer" name="cycleTime" comment="该轮第几次"></field>
		<field type="Integer" name="coins" comment="获得铜钱"></field>
		<field type="com.pwrd.war.gameserver.rep.against.AgainstRepUnitInfo" name="units" comment="每个战斗单位获取经验" list="true" macro="AgainstRepUnitInfo">
		</field>
		<field type="com.pwrd.war.gameserver.rep.against.AgainstRepItemInfo" name="items" comment="获得的物品" list="true" macro="AgainstRepItemInfo">
		</field>
		<field type="com.pwrd.war.gameserver.rep.against.AgainstRepResultInfo" name="result" comment="副本评价奖励" macro="AgainstRepResultInfo">
		</field>
	</message>
	<!-- 扫荡失败 -->
	<message type="GC_AGAINST_REP_ERR" comment="扫荡副本错误信息">
		<field type="Integer" name="errcode" comment="错误代码"></field>
		<field type="String" name="description" comment="描述"></field>
	</message>
	<!-- 结束扫荡 -->
	<message type="CG_AGAINST_REP_END" comment="结束扫荡副本"> 
	</message>
	<message type="GC_AGAINST_REP_END" comment="结束扫荡副本"> 
	</message>
	<!-- 请求扫荡加速需要多少元宝 -->
	<message type="CG_AGAINST_REP_ACC_GOLD" comment="加速扫荡副本需要元宝"> 
	</message>
	<message type="GC_AGAINST_REP_ACC_GOLD" comment="加速扫荡副本需要元宝"> 
		<field type="Integer" name="gold" comment="元宝"></field>
	</message>
	<!-- 扫荡加速 -->
	<message type="CG_AGAINST_REP_ACC" comment="加速扫荡副本"> 
	</message>
</messages>

=== cietwwl/webgame/game_tools/config/msg/model/warcraft_message.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="warcraft">
	
	<message type="CG_REQ_WARCRAFT_INFO" comment="客户端请求玩家兵法领悟信息(包括兵法领悟阶段,兵法碎片等)">
	</message>
	<message type="GC_REQ_WARCRAFT_INFO" comment="服务端返回玩家兵法领悟信息(包括兵法领悟阶段,兵法碎片等)">
		<field type="Integer" name="stage" comment="兵法领悟阶段" />
		<field type="Integer" name="grasp" comment="领悟度" />
		<field type="Integer" name="warcraftCoin" comment="兵法碎片" />
		<field type="com.pwrd.war.gameserver.warcraft.model.PrizeWarcraft"
			clientType="PrizeWarcraft" name="prizeWarcraft" comment="奖励兵法信息" list="true" macro="PrizeWarcraft">
		</field>
	</message>
	<message type="CG_REQ_WARCRAFT_TEMP_INFO" comment="客户端主动请求临时兵法背包信息">
	</message>
	<message type="GC_WARCRAFT_TEMP_INFO" comment="客服务端返回临时兵法背包信息">
		<field type="com.pwrd.war.gameserver.warcraft.model.CommonWarcraft"
			clientType="CommonWarcraft" name="warcraft" comment="兵法信息数组" list="true" macro="CommonWarcraft">
		</field>
	</message>
	<message type="CG_REQ_ALL_WARCRAFT_BAG_INFO" comment="客户端主动请求所有兵法背包信息">
	</message>
	<message type="GC_WARCRAFT_BAG" comment="返回兵法背包信息:包括兵法背包(wearerId为空)和武将兵法装备位信息">
		<field type="String" name="uuid" comment="所属者uuid" />
		<field type="String" name="wearerId" comment="佩戴者uuid" />
		<field type="Short" name="bagId" comment="背包ID:8兵法背包9玩家兵法装备位10武将兵法装备位" />
		<field type="Short" name="capacity" comment="背包的可用位置数量" />
		<field type="com.pwrd.war.gameserver.warcraft.model.CommonWarcraft"
			clientType="CommonWarcraft" name="warcraft" comment="兵法信息数组" list="true" macro="CommonWarcraft">
		</field>
	</message>
	<message type="GC_WARCRAFT_UPDATE" comment="更新单个兵法信息，客户端受到此消息就替换原来此位置的兵法">
		<field type="com.pwrd.war.gameserver.warcraft.model.CommonWarcraft"
			clientType="CommonWarcraft" name="warcraft" comment="兵法信息数组" list="true" macro="CommonWarcraft">
		</field>
	</message> 
	<message type="GC_REMOVE_WARCRAFT" comment="移除一个兵法">
		<field type="Short" name="bagId" comment="包id" />
		<field type="Short" name="index" comment="兵法在包内位置索引" />
		<field type="String" name="wearerId" comment="佩戴者uuid" />
	</message>
	<message type="GC_RESET_WARCRAFT_CAPACITY" comment="重新设置兵法装备位的容量，只可能是兵法装备位">
		<field type="Short" name="bagId" comment="包Id" />
		<field type="String" name="wearerId" comment="佩戴者uuid" />
		<field type="Short" name="capacity" comment="新的容量" />
	</message>
	<message type="CG_MOVE_WARCRAFT" comment="移动兵法，用于拖拽,合成,装备卸载动作">
		<field type="Short" name="fromBagId" comment="来源包id" />
		<field type="Short" name="fromIndex" comment="道具在来源背包内位置索引" />
		<field type="Short" name="toBagId" comment="目的包id" />
		<field type="Short" name="toIndex" comment="道具在目的包内位置索引" />
		<field type="String" name="wearerId" comment="物品佩戴者的UUID,即当前操作的武将宠物id"></field>
	</message>
	<message type="CG_DROP_WARCRAFT" comment="丢弃兵法">
		<field type="Short" name="bagId" comment="包ID" />
		<field type="Short" name="index" comment="包内位置索引" />
		<field type="String" name="wearerId" comment="物品佩戴者的UUID,即当前操作的武将宠物id"></field>
	</message>
	<message type="CG_SELL_WARCRAFT" comment="卖出兵法:只能卖出临时背包中的兵法">
		<field type="Short" name="index" comment="临时背包内位置索引" />
	</message>
	<message type="CG_GRASP_WARCRAFT" comment="领悟兵法">
		<field type="Short" name="graspType" comment="领悟类型:0普通领悟1一键领悟" />
	</message>
	<message type="CG_GET_WARCRAFT" comment="拾取兵法">
		<field type="Short" name="index" comment="临时背包内位置索引" />
	</message>
	<message type="CG_GET_ALL_WARCRAFT" comment="一键拾取">
	</message>
	<message type="CG_GET_PRIZE_WARCRAFT" comment="领取奖励兵法">
		<field type="String" name="warcraftId" comment="兵法模版id" />
	</message>
	<message type="CG_COMPOSE_All_WARCRAFT" comment="一键合成">
	</message>
	<message type="CG_SELL_All_WARCRAFT" comment="一键卖出">
	</message>
	<message type="GC_SELL_WARCRAFT_RESULT" comment="兵法卖出结果">
		<field type="Integer" name="result" comment="兵法操作结果:0失败1成功" />
		<field type="Integer" name="index" comment="兵法索引" />
		<field type="Integer" name="price" comment="兵法价格" />
	</message>
	<message type="GC_PICK_WARCRAFT_RESULT" comment="兵法卖出结果">
		<field type="Integer" name="result" comment="兵法操作结果:0失败1成功" />
		<field type="Integer" name="index" comment="兵法索引" />
	</message>
	<message type="GC_GRASP_WARCRAFT_RESULT" comment="兵法领悟结果">
		<field type="Integer" name="result" comment="兵法操作结果:0失败1成功" />
		<field type="Integer" name="index" comment="兵法索引" />
		<field type="com.pwrd.war.gameserver.warcraft.model.CommonWarcraft"
			clientType="CommonWarcraft" name="warcraft" comment="兵法信息数组" list="false" macro="CommonWarcraft">
		</field>
		<field type="Integer" name="addGrasp" comment="增加的领悟度" />
		<field type="Integer" name="stage" comment="当前领悟阶段" />
		<field type="Integer" name="lastStage" comment="上一领悟阶段" />
	</message>
</messages>

=== cietwwl/webgame/game_tools/config/msg/model/robbery_message.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="robbery">
	
	<message type="CG_ROBBERY_INDEX" comment="打开夺宝首页"> 
	</message>
	<message type="GC_ROBBERY_INDEX" comment="打开夺宝首页返回,包含所有夺宝者信息"> 
		<field type="com.pwrd.war.gameserver.robbery.RobberyShortInfo"  
		        clientType="RobberyShortInfo" name="lists" list="true" comment="运镖者信息"  > 
		    <field type="String" name="playerUUID" comment="夺宝者UUID" /> 			
			<field type="Short" name="robberyType" comment="运送的宝物类型1-5" />   
			<field type="Integer" name="allTime" comment="总时间秒" />   
			<field type="Integer" name="remainTime" comment="剩余时间秒" />  
			<field type="Integer" name="playerLevel" comment="等级" />   
			<field type="Short" name="beRobTimes" comment="被拦截次数" />   
		</field>
		<field type="Integer" name="robberyTodayTimes" comment="夺宝,今日剩余次数"></field> 
		<field type="Integer" name="robberyTodayRobTimes" comment="夺宝,今日剩余抢劫次数"></field> 
		<field type="Integer" name="robberyProtectTimes" comment="夺宝今日剩余护送次数"></field> 
		<field type="Integer" name="robberyFreeFreshTimes" comment="剩余免费刷新次数"></field> 
	</message>
	
	<message type="GC_ROBBERY_INDEX_ADD" comment="夺宝首页,有新玩家开始夺宝">
		 <field type="com.pwrd.war.gameserver.robbery.RobberyShortInfo"  
		        clientType="RobberyShortInfo" name="info"   comment="运镖者信息"  > 
		    <field type="String" name="playerUUID" comment="夺宝者UUID" /> 			
			<field type="Short" name="robberyType" comment="运送的宝物类型1-5" />   
			<field type="Integer" name="allTime" comment="总时间秒" />   
			<field type="Integer" name="remainTime" comment="剩余时间秒" />   
			<field type="Integer" name="playerLevel" comment="等级" />   
			<field type="Short" name="beRobTimes" comment="被拦截次数" />  
		</field>
	</message>
	
	<message type="CG_ROBBERY_DETAIL_INFO" comment="打开夺宝详细信息"> 
		<field type="String" name="targetUUID" comment="目标UUID"></field> 
	</message>
	<message type="GC_ROBBERY_DETAIL_INFO" comment="打开夺宝详细信息"> 
		<field type="com.pwrd.war.gameserver.robbery.RobberyInfo"  
		        clientType="RobberyInfo" name="info"   comment="运镖者信息"  macro="robberyInfo">  
		</field>
		<field type="Integer" name="remainTime" comment="剩余时间秒" />   
		<field type="Integer" name="robMoney" comment="抢劫获得铜钱" />   
		<field type="Integer" name="robPopularity" comment="抢劫获得声望" />   
	</message>
	
	<message type="CG_ROBBERY_PLYAER_INDEX" comment="打开夺宝页面"> 
	</message>
	<message type="GC_ROBBERY_PLYAER_INDEX" comment="打开夺宝页面返回的信息"> 
		<field type="Boolean" name="isFirst" comment="是否第一次打开该页面,第一次要有动画效果"></field> 
		<field type="Integer" name="robberyType" comment="运送的宝物类型1-5"></field> 
		<field type="Integer" name="refreshNeedGold" comment="本次刷新需要的元宝数量"></field> 
		<field type="Integer" name="needTime" comment="夺宝时间,单位,秒"></field> 
		<field type="Integer" name="getMoney" comment="铜钱奖励"></field> 
		<field type="Integer" name="getPopularity" comment="声望奖励"></field> 
	</message>
	
	<message type="CG_ROBBERY_FRIEND_LIST" comment="打开护送好友列表"> 
	</message>
	<message type="GC_ROBBERY_FRIEND_LIST" comment="打开护送好友列表返回"> 
		<field type="com.pwrd.war.gameserver.robbery.RobberyFriendInfo"  
		        clientType="RobberyFriendInfo" name="lists" list="true"   comment="好有信息"  > 
		    <field type="String" name="friendUUID" comment="好友UUID"></field> 
		 	<field type="String" name="friendName" comment="好友名字"></field> 
		 	<field type="Integer" name="status" comment="好友状态0正常.1护送中,2护送满"></field> 
		</field>
	</message>
	<message type="CG_ROBBERY_INVITE_FRIEND" comment="邀请好友">
		 <field type="String" name="friendUUID" comment="好友UUID"></field> 
		  <field type="Integer" name="getPopularity" comment="运送得到声望奖励"></field> 
	</message>
	<message type="GC_ROBBERY_BE_FRIEND_INVITE_FRIEND" comment="收到好友护送邀请">
		 <field type="String" name="friendUUID" comment="好友UUID"></field> 
		 <field type="String" name="friendNAME" comment="好友名字"></field> 
		 <field type="Integer" name="prizes" comment="可以得到的声望奖励"></field> 
		 <field type="Integer" name="leftTimes" comment="剩余护送次数"></field> 
	</message>
	<message type="CG_ROBBERY_BE_INVITE_FRIEND" comment="反馈被邀请结果">
		 <field type="String" name="friendUUID" comment="好友UUID"></field> 
		 <field type="Boolean" name="opinion" comment="是否同意"></field> 
	</message>
	<message type="GC_ROBBERY_INVITE_FRIEND" comment="邀请好友结果返回">
		 <field type="String" name="friendUUID" comment="好友UUID"></field> 
		 <field type="Boolean" name="opinion" comment="是否同意"></field>
	</message>
	
	<message type="CG_ROBBERY_REFRESH" comment="刷新夺宝信息">
	</message>
	
	<message type="CG_ROBBERY_START" comment="开始夺宝护送">
	</message>
	
	<message type="GC_ROBBERY_END" comment="夺宝结束获得奖励">
		<field type="Integer" name="getMoney" comment="铜钱奖励"></field> 
		<field type="Integer" name="getPopularity" comment="声望奖励"></field>
	</message>
	
	<message type="GC_ROBBERY_PROTECT_END" comment="护送夺宝结束获得奖励">
		<field type="Integer" name="getPopularity" comment="声望奖励"></field>
	</message>
	
	
	<message type="CG_ROBBERY_ROB" comment="开始抢夺宝物"> 
		<field type="String" name="targetUUID" comment="目标UUID"></field> 
	</message>
	<message type="GC_ROBBERY_ROB_RESULT" comment="开始抢夺宝物的返回结果"> 
		<field type="String" name="targetUUID" comment="目标UUID"></field> 
		<field type="Boolean" name="isOk" comment="是否可以抢劫"></field> 
		<field type="String" name="err" comment="错误原因"></field> 
	</message>
	<message type="GC_ROBBERY_ROB" comment="开始抢夺宝物结果"> 
		<field type="String" name="targetUUID" comment="目标UUID"></field> 
		<field type="String" name="targetName" comment="目标名字"></field> 
		<field type="Boolean" name="isWin" comment="是否成功"></field> 
		<field type="Integer" name="winMoney" comment="夺得铜钱"></field> 
		<field type="Integer" name="winPopularity" comment="夺得声望"></field> 
	</message>
	
	<message type="GC_ROBBERY_BE_ROB" comment="被抢夺宝物结果发给自己"> 
		<field type="String" name="attackUUID" comment="抢夺者UUID"></field> 
		<field type="String" name="attackName" comment="抢夺者姓名"></field> 
		<field type="String" name="friendName" comment="护送好友姓名"></field> 
		<field type="Boolean" name="isLoss" comment="是否被夺去s"></field> 
		<field type="Integer" name="lossMoney" comment="被夺去铜钱"></field> 
		<field type="Integer" name="lossPopularity" comment="被夺去声望"></field> 
	</message>
	
	<message type="GC_ROBBERY_PROTECT_BE_ROB" comment="护送被抢劫发给好友的结果">
		<field type="String" name="attackName" comment="抢夺者姓名"></field> 
		<field type="String" name="friendName" comment="好友姓名"></field> 
		<field type="Boolean" name="isLoss" comment="是否被夺去s"></field> 
		<field type="Integer" name="lossPopularity" comment="声望损失"></field>
	</message>
	
	
	<message type="GC_ROBBERY_BE_ROB_NEW" comment="该玩家第一次被抢"> 
		<field type="String" name="uuid" comment="被抢夺者UUID"></field> 
	</message>
</messages>

=== cietwwl/webgame/game_tools/config/msg/model/pet_message.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="pet">
	
 
	<message type="GC_PET_LIST" comment="武将列表消息">
		<field type="Short" name="maxSize" comment="武将列表总的大小" />
		<field type="Short" name="currentSize" comment="目前武将的数量" />
		<field type="com.pwrd.war.common.model.pet.PetInfo" macro="PetInfo"
			name="pets" clientType="com.pwrd.war.data.PetInfo" list="true"
			comment="武将信息列表">
		</field>
	</message>

	<message type="GC_PET_ADD" comment="增加武将消息">
		<field type="com.pwrd.war.common.model.pet.PetInfo" macro="PetInfo"
			name="pets" clientType="com.pwrd.war.data.PetInfo"
			comment="武将信息">
		</field>
	</message>
	
	<message type="GC_PET_DEL" comment="增删除武将消息">
		<field type="String" name="petUUid" comment="武将UUID" />
	</message>
	
	
	<message type="GC_PET_INFO" comment="宠物信息">
		<field type="com.pwrd.war.common.model.pet.PetInfo" macro="PetInfo"
			name="petInfo" clientType="PetInfo" comment="单个宠物信息">
		</field>
	</message>
	
	<message type="CG_PET_HIRE_LIST" comment="获取可见招募武将列表">
		<field type="String" name="pub" comment="酒馆"></field>  
	</message>

	<message type="GC_PET_HIRE_LIST" comment="获取可见招募武将列表">
		<field type="com.pwrd.war.common.model.pet.PetHireInfo" list="true" 
			name="petInfo" clientType="PetHireInfo"  comment="招募宠物信息"> 
			<field type="String" name="petSn" comment=""></field>
			<field type="Boolean" name="canHire" comment="武将是否可以招募，现在此字段废弃"></field> 
			<field type="Integer" name="hireLevel" comment=""></field>
			<field type="Integer" name="hirePopularity" comment=""></field>
			<field type="Integer" name="hireCoin" comment=""></field>
			<field type="Integer" name="hireGold" comment=""></field>
			<field type="String" name="hireItem1Sn" comment=""></field>
			<field type="Integer" name="hireItem1Num" comment=""></field>
			<field type="String" name="hireItem2Sn" comment=""></field>
			<field type="Integer" name="hireItem2Num" comment=""></field> 
		</field>
	</message>
	
	<message type="CG_PET_HIRE" comment="招募武将">  
		<field type="String" name="pub" comment="酒馆"></field>
		<field type="String" name="petSn" comment=""></field>
	</message>
	
	<message type="CG_PET_FIRE" comment="解雇武将">  
		<field type="String" name="petUUID" comment="武将uuid"></field>
	</message>
	
	<message type="CG_PET_JINGJIU" comment="武将敬酒">  
		<field type="Integer" name="id" comment="敬酒id"></field>
	</message>
	<message type="GC_PET_JINGJIU" comment="武将敬酒">  
		<field type="Boolean" name="result" comment="结果"></field>
		<field type="String" name="desc" comment="原因"></field>
	</message>
	
	<message type="GC_PET_JINGJIU_LIST" comment="敬酒信息">
		<field type="com.pwrd.war.common.model.pet.JingjiuInfo" 
			clientType="JingjiuInfoData" name="jingjiuInfo" list="true" comment="敬酒信息列表" macro="JingjiuInfo"></field>
	</message>
</messages>

=== cietwwl/webgame/game_tools/config/msg/model/monster_message.xml
<?xml version="1.0" encoding="utf-8" ?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="monster">
	
	<!-- 怪物列表 -->
	<message type="GC_MONSTER_LIST" comment="玩家第一此进入场景，发给玩家的怪物信息列表">
		<field type="com.pwrd.war.gameserver.monster.VisibleMonsterInfo"
			clientType="VisibleMonsterInfoData"
			name="monsterInfo" list="true"  comment="怪物信息"  macro="MonsterInfo">
		</field>
	</message> 
 	<!-- 增加怪物 -->
 	<message type="GC_ADD_MONSTER" comment="发给玩家的增加怪物信息列表">
		<field type="com.pwrd.war.gameserver.monster.VisibleMonsterInfo"
			clientType="VisibleMonsterInfoData"
			name="monsterInfo"   comment="怪物信息" macro="MonsterInfo">
		</field>
	</message>  
 	<!-- 减少怪物（死亡） -->
 	<message type="GC_DEL_MONSTER" comment="怪物死亡消息">
		<field type="String" name="monsterUUID" comment="明雷UUID" />
	</message> 
	<!-- 怪物移动 -->
	<message type="GC_MONSTER_MOVE" comment="在场景内有移动"> 
		<field type="String" name="monsterUUID" comment="怪物uuid" />
		<field type="Boolean" name="bAttack" comment="是否主动追击" />
		<field type="Integer" name="srcx" comment="当前x位置" />
		<field type="Integer" name="srcy" comment="当前y位置" />		
		<field type="Integer" name="tox" comment="目标x位置" />
		<field type="Integer" name="toy" comment="目标y位置" />		
		<field type="Integer" name="speed" comment="移动速度每100ms多少像素" />		
	</message>
	<!-- 怪物停止移动 -->
	<message type="GC_MONSTER_STOP_MOVE" comment="在场景内停止移动"> 
		<field type="String" name="monsterUUID" comment="怪物uuid" />
		<field type="Integer" name="srcx" comment="当前x位置" />
		<field type="Integer" name="srcy" comment="当前y位置" />	 	
	</message>
	<!-- 踩小动物 -->
	<message type="CG_STEP_MONSTER" comment="踩小动物">
		<field type="String" name="monsterUUID" comment="明雷UUID" />
	</message>
	<!-- 怪物血量减少，仅对共享怪物发 -->
	<message type="GC_MONSTER_HP_DEC" comment="怪物血量减少">
		<field type="String" name="monsterUUID" comment="明雷UUID" />
		<field type="Integer" name="lossHp" comment="丢失的hp" />
		<field type="Integer" name="curHp" comment="当前hp" />
		<field type="Integer" name="allHp" comment="总的hp" />
	</message>
</messages>

=== cietwwl/webgame/game_tools/config/msg/model/chat_message.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="chat">

	<message type="CG_CHAT_MSG" comment="客户端向服务器端发送的聊天消息">
		<field type="Integer" name="scope" comment="聊天范围" />
		<field type="String" name="destRoleName" comment="聊天消息接收的玩家" />
		<field type="String" name="destRoleUUID" comment="消息接收玩家的UUID" />
		<field type="String" name="content" comment="聊天消息" />
		<field type="Boolean" name="block" comment="是否阻止向接收者发送消息，如在玩家黑名单中，true为不发" />
		<field type="Integer" name="color" comment="聊天文字颜色"></field>
	</message>

	<message type="GC_CHAT_MSG" comment="服务器向客户端发送过滤后的聊天信息">
		<field type="Integer" name="scope" comment="聊天范围" />
		<field type="String" name="fromRoleUUID" comment="聊天消息发送者角色UUID"></field>
		<field type="String" name="fromRoleName" comment="聊天消息发送者角色名称" />
		<field type="Integer" name="fromRoleCamp" comment="聊天消息发送者阵营"></field>
		<field type="Integer" name="fromRoleSex" comment="聊天消息发送者性别"></field>
		<field type="String" name="content" comment="经过过滤后的聊天消息" />
		<field type="String" name="toRoleUUID" comment="聊天消息接受者角色UUID"></field>
		<field type="String" name="toRoleName" comment="聊天消息接受者角色名称"></field>
		<field type="Integer" name="color" comment="聊天文字颜色"></field>
	</message>
	
</messages>

=== cietwwl/webgame/game_tools/config/msg/model/transfer_vocation_message.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="transferVocation">
	<!-- 转职消息 -->
	<message type="CG_Transfer_Vocation_Message" comment="转职消息">
		<field type="String" name="petSn" comment="武将sn"></field>
		<field type="Integer" name="useType" comment="类型，1铜钱，2小元宝，3大元宝"></field>
	</message>
	
	<message type="GC_Transfer_Vocation_Result" comment="转职消息结果">
		<field type="Boolean" name="isOk" comment="是否成功"></field> 
		<field type="Integer" name="effect" comment="效果二进制，1普通，2暴击，3是否升阶，4是否升官"></field> 
		<field type="Integer" name="addStar" comment="增加星数"></field> 
		<field type="Integer" name="addExp" comment="增加的经验"></field> 
	</message>
</messages>
