=== cietwwl/webgame/game_tools/config/msg/model/message.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://com.imop.tr.message"
	xmlns:tns="http://com.imop.tr.message" elementFormDefault="qualified">
	<element name="messages" type="tns:messages"></element>

	<complexType name="messages">
		<sequence>
			<element name="constants" type="tns:constants" maxOccurs="1"
				minOccurs="0"></element>
			<element name="message" type="tns:message" maxOccurs="unbounded"
				minOccurs="0"></element>
		</sequence>
		<attribute name="module" type="string"></attribute>
		<attribute name="server" type="string"></attribute>
	</complexType>

	<complexType name="message">
		<sequence>
			<element name="field" type="tns:field" maxOccurs="unbounded"
				minOccurs="0">
			</element>
		</sequence>
		<attribute name="type" type="string"></attribute>
		<attribute name="comment" type="string"></attribute>
		<attribute name="friendQueue" type="tns:onlytrue" fixed="true"></attribute>
		<attribute name="guildQueue" type="tns:onlytrue" fixed="true"></attribute>
		<attribute name="macro" type="string"></attribute> 
	</complexType>

	<complexType name="constants">
		<sequence>
			<element name="constant" type="tns:constant" maxOccurs="unbounded"
				minOccurs="0">
			</element>
		</sequence>
	</complexType>

	<complexType name="constant">
		<simpleContent>
			<extension base="string">
				<attribute name="name" type="string"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="field">
		<sequence>
			<element name="field" type="tns:field" maxOccurs="unbounded"
				minOccurs="0">
			</element>
		</sequence>
		<attribute name="type" type="string"></attribute>
		<attribute name="clientType" type="string"></attribute>
		<attribute name="name" type="string"></attribute>
		<attribute name="list" type="tns:onlytrue" fixed="true"></attribute>
		<attribute name="comment" type="string"></attribute>
		<attribute name="macro" type="string"></attribute>
		<attribute name="subMsg" type="tns:onlytrue"></attribute>
		<attribute name="defalutValue" type="string"></attribute>
	</complexType>

	<simpleType name="onlytrue">
		<restriction base="string">
			<enumeration value="true"></enumeration>
		</restriction>
	</simpleType>
</schema>

=== cietwwl/webgame/game_tools/config/msg/model/human_message.xml
<?xml version="1.0" encoding="utf-8" ?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="human">
	
	<!-- clientType="com.pwrd.war.common.data.HumanInfoData"  -->
	<message type="GC_HUMAN_DETAIL_INFO" comment="服务器给客户端下发人物全信息">
		<field type="com.pwrd.war.common.model.human.HumanInfo"
			name="human" comment="玩家" macro="HumanDetailInfo">
		</field>
	</message>
	
	<message type="CG_ENTER_HOME" comment="客户端请求进入主城">
	</message>
	
	<message type="CG_QUERY_HUMAN_INFO" comment="客户端请求角色的属性信息">
	</message>
	
	<message type="CG_QUERY_OTHER_ROLE_INFO" comment="向服务器请求其他玩家角色信息">
		<field type="String" name="UUID" comment="请求的角色UUID" />
	</message>
	
	
	<message type="GC_SCENE_UPDATE_ROLE" comment="玩家信息发生变化，告诉场景内其他人">
		<field type="com.pwrd.war.common.model.human.HumanInfo"
			clientType="HumanSimpleInfoData"
			name="roleInfo"   comment="角色信息" macro="RoleSimpleInfo">
		</field>
	</message>
	
			 
	<!-- 玩家第一此进入场景，发给玩家的其他玩家信息列表 -->
	<message type="GC_SCENE_ROLE_LIST" comment="玩家第一此进入场景，发给玩家的其他玩家信息列表">
		<field type="com.pwrd.war.common.model.human.HumanInfo"
			clientType="HumanSimpleInfoData"
			name="roleInfo" list="true"  comment="角色信息" macro="RoleSimpleInfo">
		</field>
	</message>
	<!-- 发给其他玩家当前玩家进入消息 -->
	<message type="GC_SCENE_ADD_ROLE" comment="发给其他玩家当前玩家进入消息">
		<field type="com.pwrd.war.common.model.human.HumanInfo"
			clientType="HumanSimpleInfoData"
			name="roleInfo"   comment="角色信息" macro="RoleSimpleInfo">
		</field>
	</message>
	<!-- 发给其他玩家当前玩家离开场景消息 -->
	<message type="GC_SCENE_DEL_ROLE" comment="发给其他玩家当前玩家离开场景消息">
		<field type="String" name="UUID" comment="角色UUID" />
	</message>
	
	<message type="GC_PROPERTY_CHANGED_NUMBER" comment="用于发送数值类型的属性改变消息">
		<field type="Short" name="roleType" comment="角色类型"></field>
		<field type="String" name="roleUUID" comment="角色UUID"></field>
		<field type="com.pwrd.war.core.util.KeyValuePair&lt;Integer,Integer&gt;"  
			 clientType="KeyValuePairIntData"
			name="properties" list="true" comment="所有变化的属性">
			<field type="Integer" name="key" comment="属性索引" />
			<field type="Integer" name="value" comment="属性值" />
		</field>
	</message>
	 
	<message type="GC_PROPERTY_CHANGED_STRING" comment="用于发送字符串类型的属性改变消息">
		<field type="Short" name="roleType" comment="角色类型"></field>
		<field type="String" name="roleUUID" comment="角色UUID"></field>
		<field type="com.pwrd.war.core.util.KeyValuePair&lt;Integer,String&gt;"  
		        clientType="KeyValuePairStringData"
			name="properties" list="true" comment="所有变化的属性">
			<field type="Integer" name="key" comment="属性索引" />
			<field type="String" name="value" comment="属性值" />
		</field>
	</message>
 	
 	
 	<message type="GC_QUEUE_INFO" comment="冷却队列信息">
		<field type="Integer" name="cdType" comment="队列类型"/>
		<field type="Integer" name="index" comment="该类型的索引"/>
		<field type="Integer" name="leftTime" comment="剩余时间，单位秒"/>
		<field type="Short" name="isShow" comment="是否显示"/>
	</message>
	
 	<message type="CG_OPEN_EQUIPENHANCE_CDQUEUE" comment="开启新的强化队列">
 	</message>
 	<message type="CG_RELEASE_CDQUEUE" comment="使队列cd时间为0">
		<field type="Integer" name="index" comment="队列序号"></field>
		<field type="Integer" name="cdType" comment="队列类型,1强化装备，2属性成长"></field>
	</message>
 
	<message type="CG_ARCHIVE_LIST" comment="取得成就列表">
	</message>
	<message type="GC_ARCHIVE_LIST" comment="返回成就列表">
		<field type="com.pwrd.war.gameserver.human.domain.Archive"  
		        clientType="Archive" name="properties" list="true" comment="所有成就信息">
			<field type="String" name="uuid" comment="uuid" />
			<field type="String" name="humanUUID" comment="" />
			<field type="String" name="type" comment="" />
			<field type="Integer" name="number" comment="" />
			<field type="String" name="title" comment="" />
		</field>
	</message>
	
	<message type="CG_JOIN_CHANNEL" comment="订阅某个频道，这样就可以获取该频道的所有消息">
		<field type="String" name="channel" comment="类型(EQUIP_EHANCE，强化装备页面)" />
	</message>
	<message type="CG_UNJOIN_CHANNEL" comment="取消订阅某个频道，这样就可以获取该频道的所有消息">
		<field type="String" name="channel" comment="类型(EQUIP_EHANCE，强化装备页面)" />
	</message>
	
	<message type="CG_LEVELUP_GROW" comment="提升成长">
		<field type="Integer" name="growType" comment="提升类型"></field>
		<field type="String" name="targetUUID" comment="目标UUID"></field>
		<field type="Boolean" name="coolDown" comment="是否立即消除冷却队列"></field>
	</message> 
	<message type="CG_GROW_PROPS" comment="取得成长变化对应属性增加">
		<field type="String" name="targetUUID" comment="目标UUID"></field>
	</message>
	<message type="GC_GROW_PROPS" comment="返回成长变化对应属性增加">
		 <field type="String" name="targetUUID" comment="目标UUID"></field>
		 <field type="Integer" name="maxGrow" comment="最大成长值"></field>
		 <field type="com.pwrd.war.gameserver.human.domain.GrowChange"  
		        clientType="GrowChange" name="grows" list="true" comment="所有变化信息"> 
			<field type="Integer" name="grow" comment="成长等级" /> 
			<field type="Integer" name="needMoney" comment="需要铜钱" /> 
			<field type="Integer" name="addAtk" comment="" /> 
			<field type="Integer" name="addDef" comment="" /> 
			<field type="Integer" name="addMaxHp" comment="" /> 
			<field type="Integer" name="addAllAtk" comment="" /> 
			<field type="Integer" name="addAllDef" comment="" /> 
			<field type="Integer" name="addAllMaxHp" comment="" /> 
		</field>
	</message>
	
	<!-- 开始挂机修炼 -->
	<message type="CG_START_XIULIAN" comment="开始挂机修炼"> 
	</message>
	<message type="GC_START_XIULIAN" comment="开始挂机修炼结果">
		 <field type="Integer" name="leftTime" comment="剩余时间" /> 
		 <field type="Integer" name="allExp" comment="累计经验" /> 
		 <field type="Integer" name="zhandouli" comment="队伍战斗力" />  
		 <field type="Integer" name="xiulianLevel" comment="修炼境界等级" /> 
		 <field type="String" name="xiulianLevelName" comment="修炼境界等级名称" />  
		 <field type="Integer" name="xiulianLevelNeedGold" comment="提升境界需要多少元宝" />  
		 <field type="Integer" name="xiulianLevelDurTime" comment="提升到该境界可维持时间" />  
		 <field type="Integer" name="xiulianCollectTimes" comment="修炼可采集次数" /> 
		 <field type="Integer" name="nextRemainTime" comment="给予下次采集次数剩余多少秒" /> 
		 <field type="Integer" name="xiulianBeCollectTimes" comment="修炼被采集次数" /> 
		 <field type="Integer" name="xiulianBeCollectAllTimes" comment="修炼总被采集次数" /> 
	</message>
	<!-- 结束挂机修炼 -->
	<message type="CG_END_XIULIAN" comment="结束挂机修炼"> 
	</message>
	<message type="GC_END_XIULIAN" comment="结束挂机修炼"> 
		 <field type="Integer" name="allExp" comment="累计经验" />  
	</message>
 	<!-- 提升修炼境界 -->
 	<message type="CG_XIULIAN_UP_LEVEL" comment="提升修炼境界">  
	</message>
	
	<!-- 采集修炼标志 -->
	<message type="CG_XIULIAN_COLLECT_SYMBOL" comment="采集修炼标志"> 
		<field type="String" name="targetUUID" comment="目标UUID" />
	</message>
	<message type="GC_XIULIAN_COLLECT_SYMBOL" comment="采集修炼标志"> 
		<field type="Integer" name="getExp" comment="获得经验" />
		<field type="Integer" name="friendAddExp" comment="好友加成经验" />
		<field type="String" name="randomSymbolId" comment="随机效果ID" />
	</message>
	<message type="GC_XIULIAN_BE_COLLECT_SYMBOL" comment="被采集修炼标志"> 
		<field type="Integer" name="getExp" comment="获得经验" />
		<field type="Integer" name="friendAddExp" comment="好友加成经验" />
		<field type="String" name="randomSymbolId" comment="随机效果ID" />
	</message>
 
	
	<message type="CG_MODIFY_PERSONSIGN" comment="修改个性签名"> 
		<field type="String" name="sign" comment="个性签名" />
	</message>
	
	<message type="GC_GOLD_GROW_CRI" comment="返还元宝成长暴击">
		<field type="Integer" name="result" comment="元宝成长结果1:双倍成长2:五倍成长(暴击)" />
	</message>
	<message type="GC_JingJie_Props" comment="返还境界变化信息">
		<field type="String" name="targetUUID" comment="目标UUID"></field>
		<field type="String" name="nowName" comment="当前境界名称" /> 
		<field type="Integer" name="addAtk" comment="下一境界增加攻击值" /> 
		<field type="Integer" name="addDef" comment="下一境界增加防御值" /> 
		<field type="Integer" name="addMaxHp" comment="下一境界增加血量值" />
		<field type="Double" name="addDamage" comment="下一境界增加伤害值" />
		<field type="Integer" name="jingjie" comment="当前境界值" />
		<field type="Integer" name="nowNeedGrow" comment="当前境界值需要的成长值" />
		<field type="Integer" name="nextNeedGrow" comment="下一境界需要的成长值" />      
	</message>
	<message type="CG_JingJie_Props" comment="请求境界变化信息">
		<field type="String" name="targetUUID" comment="目标UUID"></field> 
	</message>

	<message type="GC_ONLINE_PRIZE" comment="在线奖励">
		<field type="Integer" name="buzhou" comment="步骤" />
		<field type="Integer" name="leftTime" comment="剩余可领取时间，秒" />
		<field type="String" name="prizeTip" comment="奖励提示" />
		<field type="String" name="tip" comment="提示" />
	</message>	
	<message type="CG_ONLINE_PRIZE" comment="领取奖励">
		<field type="Integer" name="buzhou" comment="步骤" />
	</message>
	<message type="GC_ONLINE_PRIZE_RES" comment="领取奖励">
		<field type="Boolean" name="res" comment="是否成功" />
	</message>
	
	<message type="GC_LOGIN_PRIZE_SHOW" comment="是否显示登陆奖励">
		<field type="Boolean" name="show" comment="true显示，false不显示" />  
	</message>	
	<message type="CG_GET_LOGIN_PRIZE" comment="取奖励信息"> 
	</message>
	<message type="GC_LOGIN_PRIZE" comment="登陆奖励">
		<field type="String" name="gotDays" comment="已领取的天" /> 
		<field type="String" name="canGetDays" comment="未领取的天" /> 
	</message>	
	<message type="CG_LOGIN_PRIZE" comment="领取登陆奖励">
		<field type="Integer" name="day" comment="领取第几天的" />
	</message>
	<message type="GC_LOGIN_PRIZE_RES" comment="领取登陆奖励">
		<field type="Boolean" name="res" comment="是否成功" />
	</message>
</messages>

=== cietwwl/webgame/game_tools/config/msg/model/secret_shop_message.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="secretShop">

	<message type="CG_SECRET_SHOP_LIST" comment="查询商品列表">
		<field type="Boolean" name="isNpc" comment="是否为npc商店"></field>
		<field type="String" name="id" comment="npc或者商店的id"></field>
		<field type="Boolean" name="isRefresh" comment="是否强制刷新"></field>
	</message>
	<message type="GC_SECRET_SHOP_LIST" comment="返回商品信息">
		<field type="Boolean" name="isNpc" comment="是否为npc商店"></field>
		<field type="String" name="id" comment="npc或者商店的id"></field>
		<field type="com.pwrd.war.common.model.secretShop.SecretShopInfo" 
			clientType="SecretShopInfoData" name="secretShopInfo" list="true" comment="神秘商店商品列表" macro="SecretShopInfo" ></field>
	</message>	
	
	<message type="CG_SECRET_SHOP_BUY" comment="购买物品">
		<field type="String" name="itemSn" comment="商品的sn"></field>
		<field type="Integer" name="number" comment="商品的数量"></field>
		<field type="Integer" name="position" comment="商品的位置"></field>
	</message>
	
	<message type="GC_SECRET_SHOP_BUY" comment="返回购买结果">
		<field type="Boolean" name="result" comment="购买结果"></field>
		<field type="String" name="content" comment="购买结果的内容"></field>
		<field type="String" name="itemSn" comment="更新为已购买的物品sn"></field>
		<field type="Integer" name="number" comment="剩余数量"></field>	
		<field type="Integer" name="position" comment="商品的位置"></field>
	</message>
	
	<message type="GC_SECRET_SHOP_TIME_REMAIN" comment="返回剩余时间">
		<field type="Long" name="time" comment="剩余时间"></field>
	</message>
	
	<message type="GC_SECRET_SHOP_BUY_INFO" comment="用户购买信息">
		<field type="com.pwrd.war.common.model.secretShop.SecretShopBuyInfo" 
			clientType="SecretShopBuyInfoData" name="secretShopBuyInfo" list="true" comment="用户购买信息列表" macro="SecretShopBuyInfo" ></field>
	</message>
	
	<message type="CG_SECRET_SHOP_PRECIOUS_INFO" comment="神秘商店珍贵物品">
	</message>
	<message type="GC_SECRET_SHOP_PRECIOUS_INFO" comment="神秘商店珍贵物品">
		<field type="com.pwrd.war.common.model.secretShop.SecretShopPreciousInfo" 
			clientType="SecretShopPreciousInfoData" name="secretShopPreciousInfo" list="true" comment="神秘商店珍贵物品" macro="SecretShopPreciousInfo" ></field>
	</message>
</messages>

=== cietwwl/webgame/game_tools/config/msg/model/mail_message.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="mail">

	<message type="CG_MAIL_LIST" comment="查询邮件列表">
		<field type="Short" name="queryIndex" comment="查询的页面索引"></field>
		<field type="Short" name="boxType" comment="邮箱类型1-inbox,2-system,3-private,4-battle,5-savebox,6-delbox"></field>
	</message>
	
	<message type="GC_MAIL_UPDATE" comment="单个邮件更新">
		<field type="com.pwrd.war.common.model.mail.MailInfo" name="mail" comment="邮件" macro="MailInfo" clientType="MailInfoData"></field>
	</message>	
	
	<message type="GC_HAS_NEW_MAIL" comment="新邮件提示">	
	</message>
	
	<message type="GC_MAIL_LIST" comment="邮件列表">
		<field type="Short" name="boxType" comment="邮箱类型1-inbox,2-system,3-private,4-battle,5-savebox,6-delbox"></field>
		<field type="Short" name="queryIndex" comment="查询的页面索引"></field>
		<field type="Short" name="totalNums" comment="总数"></field>
		<field type="com.pwrd.war.common.model.mail.MailInfo"
			clientType="MailInfoData" name="mailInfos" list="true" comment="邮件列表" macro="MailInfo">
		</field>
	</message>
	
	<message type="CG_READ_MAIL" comment="阅读邮件">
		<field type="String" name="uuid" comment="要阅读的邮件uuid"></field>
	</message>
	
	<message type="CG_SEND_MAIL" comment="发送邮件">
		<field type="String" name="recName" comment="收件人名称"></field>
		<field type="String" name="title" comment="邮件标题"></field>
		<field type="String" name="content" comment="邮件内容"></field>
		<field type="Boolean" name="isGuildMail" comment="是否为军团邮件"></field>
	</message>

	<message type="GC_SEND_MAIL" comment="发送邮件结果">
		<field type="Byte" name="resultCode" comment="发送结果"></field>
		<field type="String" name="resultMsg" comment="发送结果提示"></field>
	</message>
	
	<message type="CG_DEL_MAIL" comment="删除邮件">
		<field type="String" name="uuid" comment="要删除的邮件uuid"></field>
	</message>
	
	<message type="CG_DEL_ALL_MAIL" comment="删除所有邮件">
		<field type="String" name="uuidlist" list="true" comment="要删除的所有邮件uuid"></field>
	</message>
	
	<message type="CG_SAVE_MAIL" comment="保存邮件">
		<field type="String" name="uuid" comment="要保存的邮件uuid"></field>
	</message>
	
	<message type="CG_SEND_GUILD_MAIL" comment="发送军团邮件">
		<field type="String" name="title" comment="邮件标题"></field>
		<field type="String" name="content" comment="邮件内容"></field>
	</message>

</messages>

=== cietwwl/webgame/game_tools/config/msg/model/player_message.xml
<?xml version="1.0" encoding="utf-8" ?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="player">

 
	
	<message type="CG_PLAYER_COOKIE_LOGIN" comment="用户cookie登录">
		<field type="String" name="cookieValue" comment="cookie值"></field>
	</message>
	
	<message type="GC_LOGIN_SUCCESS" comment="通知用户登录成功"/>
	<message type="GC_LOGIN_FAILED" comment="通知用户登录失败">
		<field type="String" name="failMsg" comment="失败信息"></field>
	</message>
	
	<message type="GC_ROLE_INFO" comment="角色信息">
	<!-- 
		<field type="com.pwrd.war.gameserver.player.RoleInfo" name="roleInfo"  comment="角色信息" macro="RoleInfo"></field>  -->
		<field type="String" name="roleUUID" comment="角色的uuid"></field> 
		<field type="String" name="name" comment="角色名字"></field> 
		<field type="Integer" name="sex" comment="选择的性别"></field>
		<field type="Integer" name="vocation" comment="选择的职业"></field>
		<field type="Integer" name="camp" comment="选择的阵营 "></field>
	</message>
	
 
	<message type="CG_CREATE_ROLE" comment="创建角色">
		<field type="String" name="name" comment="角色名字"></field> 
		<field type="Integer" name="sex" comment="选择的性别"></field>
		<field type="Integer" name="vocation" comment="选择的职业"></field>
		<field type="Integer" name="camp" comment="选择的阵营 "></field>
	</message>	
	
	<message type="GC_FAILED_MSG" comment="GS向CLIENT发送操作失败消息">
		<field type="Short" name="errorNo" comment="错误号"></field>
		<field type="String" name="msg" comment="错误提示信息"></field>
	</message>
	
	<!-- 加载角色数据 实际就是选角色 -->
	<message type="CG_PLAYER_ENTER" comment="选择角色进入游戏场景">
		<field type="String" name="roleUUID" comment="角色的uuid"></field>
	</message>
	
	<!-- 服务器角色信息加载完毕 发送场景信息 客户端加载资源 -->
	<message type="GC_SCENE_INFO" comment="玩家进入场景的信息">  
	</message>
	
	<!-- 客户端加载资源加载完毕  -->
	<message type="CG_ENTER_SCENE" comment="玩家可以进入场景">
		<field type="Integer" name="line" comment="分线号，-1表示随机分配"></field>
	</message>
	
	<!-- 服务器进入gaming状态前,进入场景后,客户端收到消息 -->
	<message type="GC_ENTER_SCENE" comment="玩家已经进入场景"> 
	</message>
	
	<message type="GC_NOTIFY_EXCEPTION" comment="通知客户端">
		<field type="Integer" name="code" comment="错误码"></field>
		<field type="String" name="msg" comment="错误信息，如果为空就显示默认的"></field>
	</message>
	<!-- 
	<message type="CG_PLAYER_CHARGE_DIAMOND" comment="玩家充值平台币">
		<field type="Integer" name="mmCost" comment="兑换的平台币数量"></field>
	</message>
	
	<message type="GC_PLAYER_CHARGE_DIAMOND" comment="兑换成功">
		<field type="Integer" name="mmBalance" comment="平台币余额"/>
	</message>
	
	<message type="CG_PLAYER_QUERY_ACCOUNT" comment="查询账户余额">	
	</message>
	
	<message type="GC_PLAYER_QUERY_ACCOUNT" comment="查询账户余额的结果">
		<field type="Integer" name="mmBalance" comment="MM余额"></field>
	</message>
	 -->
	<message type="CG_PLAYER_GUIDE" comment="新手引导">
		<field type="String" name="guideId" comment=""></field>
	</message>
	
	<message type="CG_PLAYER_GUIDE_LIST" comment="新手引导查询"> 
	</message>
	<message type="GC_PLAYER_GUIDE_LIST" comment="已完成的新手引导">
		<field type="String" name="guideIds" comment=""></field>
	</message>
	 
</messages>

=== cietwwl/webgame/game_tools/config/msg/model/quest_message.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="quest">

	<message type="CG_QUEST_LIST" comment="请求任务列表">
	</message>
	
	<message type="GC_QUEST_LIST" comment="返回任务列表">
		<field type="com.pwrd.war.common.model.quest.QuestInfo"
			clientType="QuestData" name="questInfos" list="true" comment="任务列表" macro="QuestInfo">
		</field>
	</message>
	
	<message type="GC_QUEST_UPDATE" comment="任务更新消息">
		<field type="com.pwrd.war.common.model.quest.QuestInfo"
			clientType="QuestData" name="questInfo" comment="单个任务" macro="QuestInfo">
		</field>
	</message>
	
	<message type="GC_FINISH_QUEST" comment="完成任务结果">
		<field type="Integer" name="questId" comment="任务Id"></field>
	</message>
	
	<message type="CG_ACCEPT_QUEST" comment="接受任务">
		<field type="Integer" name="questId" comment="任务Id"></field>
	</message>
	
	<message type="CG_GIVE_UP_QUEST" comment="放弃已接任务">
		<field type="Integer" name="questId" comment="任务Id"></field>
	</message>
	
	<message type="CG_FINISH_QUEST" comment="完成任务">
		<field type="Integer" name="questId" comment="任务Id"></field>
	</message>
	
</messages>

=== cietwwl/webgame/game_tools/config/msg/model/tree_message.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="tree">
	<message type="CG_TREE_INFO" comment="摇钱树信息">
	</message>
	
	<message type="GC_TREE_INFO" comment="摇钱">
		<field type="Integer" name="shakeTimes" comment="当天摇钱次数"></field>
		<field type="Integer" name="totalTimes" comment="最大摇钱次数"></field>
		<field type="Integer" name="costGold" comment="一次花多少元宝"></field>
		<field type="Integer" name="getCoin" comment="一次得多少铜钱"></field>
		<field type="Boolean" name="batchFlag" comment="能够进行批量摇钱"></field>
		<field type="Integer" name="costBatch" comment="批量一次花多少元宝"></field>
		
	</message>
	
	<message type="CG_TREE_SHAKE" comment="摇钱">
	</message>
	<message type="CG_TREE_SHAKE_BATCH" comment="批量摇钱">
	</message>
	<message type="GC_TREE_SHAKE" comment="返回摇钱信息">
		<field type="Boolean" name="result" comment="返回结果"></field>
		<field type="String" name="desc" comment="返回结果描述"></field>
	</message>	
	
	<message type="CG_WATER_INFO" comment="浇水和果实信息">
	</message>
	
	<message type="GC_WATER_INFO" comment="返回浇水和果实信息">
		<field type="Integer" name="waterTimes" comment="给自己的浇水次数"></field>
		<field type="Integer" name="waterTime" comment="浇水的冷却时间"></field>
		<field type="Integer" name="friendWaterTimes" comment="给好友的浇水次数"></field>
		<field type="Integer" name="curTreeExp" comment="摇钱树当前经验"></field>
		<field type="Integer" name="maxTreeExp" comment="摇钱树升级经验"></field>
		<field type="Integer" name="treeLevel" comment="摇钱树等级"></field>
		<field type="Integer" name="fruitLevel" comment="已经领取的果实等级"></field>		
	</message>
	
	<message type="CG_WATER_MYSELF" comment="给自己浇水">
	</message>
	
	<message type="CG_WATER_FRIEND" comment="给好友浇水">
		<field type="String" name="friendName" comment="好友名称" />
		<field type="String" name="friendUUID" comment="好友UUID" />
	</message>
	
	<message type="GC_WATER_RESULT" comment="浇水结果">
		<field type="Boolean" name="result" comment="返回结果"></field>
		<field type="String" name="desc" comment="返回结果描述"></field>
	</message>
	
	<message type="CG_GET_FRUIT" comment="获取果实">
		<field type="Integer" name="fruitLevel" comment="获取果实等级"></field>
	</message>
	
	<message type="GC_GET_FRUIT" comment="返回获取果实结果">
		<field type="Boolean" name="result" comment="返回结果"></field>
		<field type="String" name="desc" comment="返回结果描述"></field>
	</message>
	
	<message type="CG_GET_WATER_RECORD" comment="获取浇水记录">
	</message>
	
	<message type="GC_GET_WATER_RECORD" comment="获取浇水记录">
		<field type="com.pwrd.war.gameserver.tree.HumanTreeWaterInfo"  
		        clientType="HumanTreeWaterInfo" name="humanTreeWaterInfo" list="true" comment="好友信息列表" macro="humanTreeWaterInfo">  
		</field>
	</message>
	
	<message type="CG_WATER_FRIEND_BATCH" comment="一键浇水">
		
	</message>
	
	<message type="CG_FRIEND_WATER_INFO" comment="浇水和果实信息">
		<field type="String" name="friendUuid" comment="好友uuid"></field>
		<field type="String" name="friendName" comment="好友名称"></field>
	</message>
	
	<message type="GC_FRIEND_WATER_INFO" comment="返回浇水和果实信息">
		<field type="Integer" name="vocation" comment="玩家职业"></field>
		<field type="Integer" name="curTreeExp" comment="摇钱树当前经验"></field>
		<field type="Integer" name="maxTreeExp" comment="摇钱树升级经验"></field>
		<field type="Integer" name="treeLevel" comment="摇钱树等级"></field>
	</message>
	
	<message type="CG_GET_FRIEND_WATER_RECORD" comment="获取浇水记录">
		<field type="String" name="friendUuid" comment="好友uuid"></field>
		<field type="String" name="friendName" comment="好友名称"></field>
	</message>
	
	<message type="GC_GET_FRIEND_WATER_RECORD" comment="获取浇水记录">
		<field type="com.pwrd.war.gameserver.tree.HumanTreeWaterInfo"  
		        clientType="HumanTreeWaterInfo" name="humanTreeWaterInfo" list="true" comment="好友信息列表" macro="humanTreeWaterInfo">  
		</field>
	</message>
</messages>

=== cietwwl/webgame/game_tools/config/msg/model/Tower_message.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns="http://com.pwrd.war.message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.pwrd.war.message message.xsd" module="tower">

	<message type="CG_TOWER_INIT" comment="将星云路信息">
	</message>
	
	<message type="CG_TOWER_INFO" comment="将星云路信息">
		<field type="Integer" name="constellationId" comment="星座id"></field>
	</message>
	
	<message type="GC_TOWER_INFO" comment="返回将星云路信息">
		<field type="Integer" name="constellationId" comment="星座id"></field>
		<field type="Integer" name="starNumber" comment="第几星"></field>
		<field type="Integer" name="maxStarNumber" comment="当前星座最大星"></field>
		<field type="Integer" name="refreshTimes" comment="刷新次数"></field>	
		<field type="Boolean" name="secretFlag" comment="是否有神秘星"></field>	
	</message>
	
	<message type="CG_TOWER_REFRESH" comment="将星云路刷新">
		<field type="Integer" name="constellationId" comment="星座id"></field>
	</message>
	
	<message type="GC_TOWER_REFRESH" comment="返回将星云路刷新">
		<field type="Boolean" name="result" comment="刷新结果"></field>
		<field type="String" name="desc" comment="结果描述"></field>		
	</message>
	
	<message type="CG_TOWER_SPEEDUP" comment="将星云路加速">
		<field type="Integer" name="constellationId" comment="星座id"></field>
	</message>
	
	<message type="GC_TOWER_SPEEDUP" comment="返回将星云路加速">
		<field type="Boolean" name="result" comment="加速结果"></field>
		<field type="String" name="desc" comment="结果描述"></field>		
	</message>
	
	<message type="CG_TOWER_BATTLE" comment="将星云路战斗">
		<field type="Integer" name="constellationId" comment="星座id"></field>
		<field type="Integer" name="starNumber" comment="第几星"></field>
		<field type="Boolean" name="secretFlag" comment="是否为神秘星"></field>
	</message>
	
	<message type="GC_TOWER_BATTLE" comment="返回将星云路能否战斗结果">
		<field type="Boolean" name="result" comment="战斗结果"></field>
		<field type="String" name="desc" comment="结果描述"></field>	
	</message>
	
	<message type="GC_TOWER_BATTLE_RESULT" comment="返回将星云路战斗结果">
		<field type="Boolean" name="result" comment="战斗结果"></field>
		<field type="String" name="starSoul" comment="获得星魂"></field>	
	</message>
	
	<message type="GC_TOWER_SECRETE" comment="返回神秘星">
		<field type="Integer" name="constellationId" comment="星座id"></field>
		<field type="String" name="secretId" comment="神秘星id"></field>
	</message>
	
	<message type="GC_TOWER_BAG" comment="返回星魂背包容量">
		<field type="Integer" name="capacity" comment="容量"></field>
	</message>
	
	<message type="CG_TOWER_AUTO_START" comment="开始自动挑战">
		<field type="Integer" name="constellationId" comment="星座id"></field>
	</message>
	
	<message type="GC_TOWER_AUTO_START" comment="返回开始自动挑战">
		<field type="Boolean" name="result" comment="自动挑战结果"></field>
		<field type="String" name="desc" comment="结果描述"></field>
	</message>
	
	<message type="GC_TOWER_AUTO_COMPLETE_ONE" comment="自动挑战完成一层">
		<field type="Integer" name="constellationId" comment="星座id"></field>
		<field type="Integer" name="starNumber" comment="当前星"></field>
		<field type="String" name="starSoul" comment="获得星魂"></field>	
	</message>
	
	<message type="GC_TOWER_AUTO_COMPLETE" comment="自动挑战完成">
		<field type="String" name="desc" comment="完成原因"></field>	
	</message>
	
	<message type="CG_TOWER_AUTO_CANCEL" comment="取消自动挑战">
		<field type="Integer" name="constellationId" comment="星座id"></field>
	</message>
	
	<message type="GC_TOWER_AUTO_CANCEL" comment="取消自动挑战">
		<field type="Integer" name="starNumber" comment="当前星"></field>	
	</message>
	
</messages>
